### ISSUE TITLE
Is the pretrained model provided ? 

### ISSUE THREAD

**Issue by stevenlsw** [enriccorona/GanHand#1]
Hi, 

I am very interested in your work and willing to use the affordance dataset. Could you provide a pre-trained model.  And I also  notice that imgnames.npy file used in the dataset is missing. Looking forward to your reply.

**Comment by enriccorona** [comment]
Hi,

Yes, the pre-trained model can be downloaded from this link:
https://drive.google.com/file/d/19462M8s3tEXe_1_riHuvQegLxzdX-kl2/view?usp=sharing

I'll update the README file with the instructions to set this up. You have to place this folder uncompressed inside a folder called checkpoint, on the main folder of this code. For the dataset, you have to download the YCB-Affordance dataset from here: https://github.com/enriccorona/YCB_Affordance, and modify the path to wherever you place the dataset . This includes the imgnames.npy file as well

Let me know if you have any problems with that,
Enric

**Comment by stevenlsw** [comment]
Great, thanks so much for the quick response

**Comment by stevenlsw** [comment]
The links to the predictions of the 6d pose on YCB dataset seems wrong, would you please provide a new one for the ycb predictions, thanks.

**Comment by enriccorona** [comment]
Thanks for mentioning that, I updated the link of the 6DOF predictions of the objects in https://drive.google.com/file/d/17WEN8vhel6Ico-lGDtrcxu7XFemVi4qN/view.
Also just updated the file restrictions so both these predictions and the model should be downloadable now!

**Comment by stevenlsw** [comment]
sorry to bother again, it seems that the pre-trained zip file is corrupted, specifically, the opt_epoch_13_id_G.pth is broken.

**Comment by enriccorona** [comment]
Right, it seems it got corrupted because of some memory issues, can you try now downloading the same model from the same link: https://drive.google.com/file/d/19462M8s3tEXe_1_riHuvQegLxzdX-kl2/view

**Comment by stevenlsw** [comment]
thanks, it works now
