### ISSUE TITLE
How to test on obman dataset?

### ISSUE THREAD

**Issue by hwjiang1510** [enriccorona/GanHand#2]
as title

**Comment by enriccorona** [comment]
Hi, We don't plan to release the code to run on the ObMan dataset. 
We did some changes on the dataset, like changing the background on all images, normalizing the scales of the object and preprocessing the meshes, so it would take some effort to further release that. 

For those experiments, we used a simpler version of the model released here, which only uses RGB (compared to this one where we use RGB + Mask), and grasps a single object. If you're interested in the object reconstruction pipeline, check the AtlasNet used in the ObMan paper, which we adapted to this project: https://github.com/hassony2/obman_train
